// ! array that contains each shop items
let cartItems = [
  {
    id: "product-1",
    productName: "Oraimo 10000mah Power-Bank OPB-P118D",
    productImg: "/img/powerbank.jpeg",
    productPrice: 18590,
    productQuantity: 1,
    like: false,
  },
  {
    id: "product-2",
    productName: "Leather Boot ",
    productImg: "/img/img-12.png",
    productPrice: 25500,
    productQuantity: 1,
    like: false,
  },
  {
    id: "product-3",
    productName: "Oraimo cord - 2 in 1 ",
    productImg: "/img/cord2in1.jpeg",
    productPrice: 1500,
    productQuantity: 1,
    like: false,
  },
  {
    id: "product-4",
    productName: "Oraimo Clipper",
    productImg: "/img/clipper.jpeg",
    productPrice: 15000,
    productQuantity: 1,
    like: false,
  },
  {
    id: "product-5",
    productName: "Oraimo Speaker",
    productImg: "/img/speaker.jpeg",
    productPrice: 12000,
    productQuantity: 1,
    like: false,
  },
  {
    id: "product-6",
    productName: "Basic Cap",
    productImg: "/img/img-11.png",
    productPrice: 3500,
    productQuantity: 1,
    like: false,
  },
  // {
  //   id: "product-7",
  //   productName: "Men's Tie",
  //   productImg: "/img/img-5.png",
  //   productPrice: 2500,
  //   productQuantity: 1,
  //   like: false,
  // },
  {
    id: "product-8",
    productName: "Demim pants",
    productImg: "/img/img-10.png",
    productPrice: 15000,
    productQuantity: 1,
    like: false,
  },
];
